- name: Setup Postgresql
  hosts: all
  tasks:

    - name: Install epel repo
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present

    - name: Install postgresql-server and postgresql-contrib
      yum:
        name:
          - postgresql-contrib
          - postgresql-server

    - name: Take ownership of /var/lib/pgsql/data
      file:
        path: /var/lib/pgsql/data
        owner: postgres
        group: postgres


    - name: Setup Postgresql-db
      command: postgresql-setup initdb

    - name: Edit postgresql.conf-1
      lineinfile:
           path: /var/lib/pgsql/data/postgresql.conf
           regexp: '#shared_buffers='
           line: 'shared_buffers=2048MB'

    - name: Edit postgresql.conf-2
      lineinfile:
           path: /var/lib/pgsql/data/postgresql.conf
           regexp: '#effective_cache_size='
           line: 'effective_cache_size=4096MB'

    - name: Edit postgresql.conf-3
      lineinfile:
         path: /var/lib/pgsql/data/postgresql.conf
         regexp: '#checkpoint_segments='
         line: 'checkpoint_segments=8'


    - name: Start postgresql.service
      systemd:
        state: started
        name: postgresql
